### ISSUE TITLE
transition: 0.2s; not detected

### ISSUE THREAD

**Issue by Nemo64** [kristerkari/stylelint-high-performance-animation#1]
`transition: 0.2s` is not detected as what it is: `transition: all 0.2s`.
That is the most common problem I see in my projects.

**Comment by kristerkari** [comment]
Thanks @Nemo64, I'll implement a fix for that

**Comment by kristerkari** [comment]
There is now a PR to fix this by adding support for detecting `all` for transition-property: 
#2

**Comment by kristerkari** [comment]
The fix is included in version 1.1.0
