### ISSUE TITLE
stylelint 12.x as peer dependency

### ISSUE THREAD

**Issue by ybiquitous** [kristerkari/stylelint-high-performance-animation#10]
Hi,

stylelint [12.0.0](https://github.com/stylelint/stylelint/releases/tag/12.0.0) was released but do you have a plan to update the peer dependency?

https://github.com/kristerkari/stylelint-high-performance-animation/blob/8a1227dc0f61e35506f55f04181f60dfd6a1b355/package.json#L47

I get the following error when installing `stylelint@12` and `stylelint-high-performance-animation`. 😢 

> npm ERR! peer dep missing: stylelint@^7.0.0 || ^8.0.0 || ^9.0.0 || ^10.0.0 || ^11.0.0, required by stylelint-high-performance-animation@1.3.0

It would be great if you could consider it.
Thanks.

**Comment by kristerkari** [comment]
Yeah, I'll need to update all my plugins once again :) For now you can just ignore the warning.

**Comment by ybiquitous** [comment]
OK, thanks 👍

**Comment by kristerkari** [comment]
Since there was a PR for it, I went and released a new version with stylelint 12 support already: https://github.com/kristerkari/stylelint-high-performance-animation/releases/tag/1.4.0

**Comment by ybiquitous** [comment]
Thank you so much! 😊
