### ISSUE TITLE
background-color cause layout

### ISSUE THREAD

**Issue by Nemo64** [kristerkari/stylelint-high-performance-animation#3]
`background-color` is in the list of properties that cause layout while `background` is in the list of paint properties.

Can I assume that is a mistake? I think `background-color` is a paint property too. Or if it isn't, than the `background` shorthand probably isn't either.

**Comment by kristerkari** [comment]
I am of course willing to fix the properties, if we can from somewhere confirm that they are currently wrong.

**Comment by Nemo64** [comment]
Interesting article but its form 2013.

Anyways I did a few tests using this fiddle: https://jsfiddle.net/6gpoah9r/5/

This is with a "slow" height animation:
![bildschirmfoto 2018-08-30 um 10 00 01](https://user-images.githubusercontent.com/1749936/44838238-ef249480-ac3b-11e8-90aa-56a8595ebe26.png)

This is with a "background-color" animation:
![bildschirmfoto 2018-08-30 um 10 00 45](https://user-images.githubusercontent.com/1749936/44838255-f9469300-ac3b-11e8-9831-a146d638f54d.png)

And this is with a "background" animation:
![bildschirmfoto 2018-08-30 um 10 01 52](https://user-images.githubusercontent.com/1749936/44838275-04012800-ac3c-11e8-8c98-0ba0baaabd2b.png)

There are some repaints that I assume are related to the iframe structure of jsfiddle. But the important part is that the "layout" step is missing. 

However I found another resource: https://csstriggers.com
It seems that the layout is triggered in all webkit browsers using all background properties (which chrome isn't anymore).

**Comment by Nemo64** [comment]
So it seems like webkit basically always relayouts... https://github.com/GoogleChromeLabs/css-triggers/issues/21

**Comment by kristerkari** [comment]
Thanks for having a proper look at this! 

I did not know about csstriggers website. It seems like a very good source for this plugin!

Maybe all of the background props should be removed to layout category since they cause layout in Webkit (but not Blink)?

**Comment by kristerkari** [comment]
Actually, I could write a script that scrapes the data from here and creates the layout / paint groups based on that:
https://github.com/GoogleChromeLabs/css-triggers/tree/master/data

**Comment by Nemo64** [comment]
If you'd go by the table than the only property that does not cause a relayout in any browser is `cursor`- which can't even be animated. Maybe just define "blink" as the standard since every browser should animate like it? I mean safari is fast with opacity/transform animations... i guess this table tells us which _javascript_ changes trigger layout/paint since safari does not have this blurry "not repainted" state that chrome has to optimise subsequent changes.

**Comment by Nemo64** [comment]
I think I am correct. I did some testing (fiddle here: https://jsfiddle.net/51msjd4y/10/).

This is how the timeline looks in safari with a keyframe animation.
![bildschirmfoto 2018-08-30 um 18 52 54](https://user-images.githubusercontent.com/1749936/44866717-4d766500-ac86-11e8-9e62-21092f038095.png)

And this is how the timeline looks with a js animation:
![bildschirmfoto 2018-08-30 um 18 54 56](https://user-images.githubusercontent.com/1749936/44866741-5b2bea80-ac86-11e8-869f-b12532831d4c.png)

so.... I guess i'd go with what blink is good at at subsequent changes since that looks reasonable.

**Comment by Nemo64** [comment]
Here another updated fiddle: https://jsfiddle.net/51msjd4y/13/

This time with tweaked scaling to show what I mean:
![bildschirmfoto 2018-08-30 um 18 58 51](https://user-images.githubusercontent.com/1749936/44866935-d1c8e800-ac86-11e8-8afe-44d0a84fe6c7.png)

Left: js scaled. Text is sharp because it is redrawn
Right: css animation scaled. Text is blurry because safari did not redraw it.

**Comment by Nemo64** [comment]
honestly i'd just go for moving `background-color` and maybe also `border-color` to the paint list and call it a day.

if you want the list more automated go with csstrigers/subsequent updates/blink since that list looks reasonable but is of course a bit cruel.

**Comment by kristerkari** [comment]
> honestly i'd just go for moving background-color and maybe also border-color to the paint list and call it a day.

This is probably the right thing to do for now. We can come back to the issue if we find a more up-to-date resource for the layout/paint props.

**Comment by kristerkari** [comment]
This is now fixed in v1.1.1. Thanks a lot for helping!
