### ISSUE TITLE
Not getting warnings for logical properties

### ISSUE THREAD

**Issue by t0byman** [kristerkari/stylelint-high-performance-animation#36]
Would you kindly update your stylelint plugin so that we also get warnings when typing logical properties? For example:
`transition: margin-block-start .25s ease-out;` which is a logical version of `transition: margin-top .25s ease-out;`.

You can find a full list of logical properties here: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Logical_Properties

**Comment by kristerkari** [comment]
Alright, looks like there is quite a list of props to be supported.

**Comment by t0byman** [comment]
My man! Thank you so much!
